### ISSUE TITLE
Move to leaflet-extras

### ISSUE THREAD

**Issue by nhnb** [leaflet-extras/leaflet-map#21]
Hi @brunob,

how do we organize the move to leaflet-extras? 

As discussed in various places, the idea was to consolidate the implementation from @prtksxna and mine, which we did in autumn. And then move it to an official leaflet-repository. Leaflet, however, prefers to put it into leaflet-extras, which is fine with me. 

With polymer 1.0 being released today and breaking compatibility, now is a good time to move the consolidated component to leaflet-extras. The Polymer 0.5 based components can stay at their old locations for a couple of month with a big hint at the top.

Current status is this: The port to Polymer 0.9 (compatible with 1.0) is in the 0.9 branch of https://github.com/nhnb/leaflet-map/ I have a local gh_page branch for the 1.0 website.

Please create a leaflet-extras/leaflet-map repository and grant commit access to @prtksxna and me.

Thank you
Hendrik

**Comment by brunob** [comment]
I think the best way is to transfer your repo to @leaflet-extras organization, and after that i will add commit access to this one for you and @prtksxna :)

**Comment by nhnb** [comment]
Oh, I was not aware that github has a mechanism for transferring repos. But when I try to use that, I get the error message, that I don't have admin rights on leaflet-extras.

**Comment by brunob** [comment]
Ok, i was quite sure about this when i was posting my comment :p If you give me admin access to the repo, i will be able to transfer it to @leaflet-extras.

**Comment by nhnb** [comment]
I added you to the contributor list. Hopefully this is sufficient. I did not find any setting about admin access.

**Comment by brunob** [comment]
Ok, let me look at this...

**Comment by brunob** [comment]
I can't see settings button on the repo, you have to add me to collaborators with full access in settings/collaboration page of the repo.

**Comment by nhnb** [comment]
There seems to be no way to define permissions on the contributors settings page:
![bildschirmfoto vom 2015-05-28 11 56 22](https://cloud.githubusercontent.com/assets/364184/7857467/d7aba952-0530-11e5-8848-16a440d33bec.png)

https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization suggest to create a new, temporary admin group on target organization.

**Comment by brunob** [comment]
Ok, i think i have to add you to @leaflet-extras organization in order to allow you to transfer your repo to it. Any problem about that @leaflet-extras ?

**Comment by brunob** [comment]
Ok @nhnb i've created a leaflet-map team on leaflet-extras orga, you should now be able to transfer your repo to leaflet-extras :)

**Comment by brunob** [comment]
https://github.com/leaflet-extras/leaflet-map (y) @nhnb

**Comment by nhnb** [comment]
Thank you, it seems to work fine, modulo the expected problems. I invited @prtksxna and will publish 1.0 with a fixed website tomorrow night. (Perhaps tonight but that depends on other tasks).
