### ISSUE TITLE
Style geojson features

### ISSUE THREAD

**Issue by maptastik** [leaflet-extras/leaflet-map#30]
I'm having trouble overriding the default style for features brought into my map using **leaflet-geojson**. It seems from the examples to be possible to set styles with components like **leaflet-polygon**, **leaflet-circle** etc. For instance, you can assign a polygon a color like this: `<leaflet-polygon color="#f00">...</leaflet-polygon>`. 

However if I do something similar with **leaflet-geojson** the features are drawn with Leaflet's default style for the geometry type. Following the model from the **leaflet-polygon** example, I tried this to make my features yellow:

 `<leaflet-geojson data="[[data]]" color:"#f7ff00"></leaflet-geojson>`

But the default line style is returned:

![leafletcomp1](https://cloud.githubusercontent.com/assets/3319507/8642577/2d9e0e5e-28f4-11e5-8dec-d42f286a6e55.JPG)
([source](https://github.com/maptastik/leaflet-component/blob/gh-pages/index.html) | [live example](http://maptastik.github.io/leaflet-component/))

I guess my question is, **Is there a way to style *leaflet-geojson* features using an HTML attribute?**

- If yes, what might that look like?
- If no, any suggestions on how I might begin to apply my own styles to features mapped via 'leaflet-geojson'?

**Comment by nhnb** [comment]
Polygons and cicles extend [path](http://leafletjs.com/reference.html#path), which has a color property for example. There are no such properties for [geojson](http://leafletjs.com/reference.html#geojson) or any of its parents. There is a style-callback and a setStyle method through, which might be helpful. This needs more investigation.

**Comment by nhnb** [comment]
Thank you for your contribution. I just released version 1.1.0 which contains your pull request.
