### ISSUE TITLE
fitToMarkers not working

### ISSUE THREAD

**Issue by LostInBrittany** [leaflet-extras/leaflet-map#31]
In the current version of the project, the `fitToMarkers` attribute doesn't work.

Here you have an example:

    <leaflet-map fit-to-markers>
	<leaflet-marker latitude="51.5" longitude="-0.10" title="Transparent" opacity="0.6">
	</leaflet-marker>

	<leaflet-marker latitude="51.5" longitude="-0.09" title="Popup Demo">
		<b>Bold</b>
		<p>Text</p>
	</leaflet-marker>
    </leaflet-map>

The `fitToMarkers` attribute should make the component to scan all the layers, get the lat-lng for all the features (here the two  markers) and use them as bounding box for the map. But it doesn't anything.

The problem, AFAIK, is in the `fitToMarkersChanged` event:

             fitToMarkersChanged: function () {
			if ( this.map && this.fitToMarkers) {
				var bounds = [];
				for( var i = 0, f; f = this.features[i]; i++ ) {
					if ( f.latitude && f.longitude ) {
						bounds.push( [ f.latitude, f.longitude ] );
					}
				}
				if ( bounds.length > 0 ) {
					this.map.fitBounds( bounds );
					this.map.invalidateSize();
				}
			}
		}

where `this.features` doesn't exist (anymore?).

In other, in current Polymer version, the event isn't fired when an initial value to `fitToMarkers` is given.

**Comment by nhnb** [comment]
Hi, thanks for the bug report and pull request. In addition to applying it, I added the missing property observer.
