### ISSUE TITLE
zoom-control='false' does not work

### ISSUE THREAD

**Issue by JustinCase1089** [leaflet-extras/leaflet-map#33]
I cant get zoom-control='false' to work

**Comment by nhnb** [comment]
Urks, as far as I can tell, there is no way in HTML to set an attribute to false, if it has a default value of true: http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#boolean-attributes

At the moment, I can only think of having "no-xxx" attributes with inversed logic. But that does not seem to be a good idea.

**Comment by JustinCase1089** [comment]
Yes, that does seem to be the only option, but still, it is the way it is done elsewhere. I don't think its a bad solution

**Comment by nhnb** [comment]
I just released version 1.1.0, in which the attribute is renamed to `no-zoom-control`.

**Comment by JustinCase1089** [comment]
Actually ... I have dug a bit into it and must admit that it is really messy the approach for handlign booleans. The main problem as I see it is that you cannot bind to a property of type boolean on an element. There are suggestions e.g. here https://github.com/Polymer/polymer/issues/1812 to set the type to Object which would allow databinding to it.
