### ISSUE TITLE
License problems

### ISSUE THREAD

**Issue by davidcalhoun** [leaflet-extras/leaflet-map#35]
Thanks a lot for offering this up - I've been using it in my workplace and it's working pretty well.

I'm trying to import leaflet-map into my company's "third party" code directory but I'm having a problem with the language in the license, specifically this part:

```leaflet-map is based on polymer and leaflet. Small parts of leaflet, especially the api documentation, have been copied into leaflet-map files.```

It's not clear whether "based on" means.  Is it derived (pieces of Polymer core code interspersed throughout), or is it just a certain subdirectory, or does it simply implement a Polymer element?  I suspect the very latter, but I just want it to be clear.

Thanks!

**Comment by nhnb** [comment]
&lt;leaflet-map> uses polymer and requires it to be present in a sibling folder called polymer. Polymer is not included.
