### ISSUE TITLE
No Touch Support

### ISSUE THREAD

**Issue by fooloomanzii** [leaflet-extras/leaflet-map#37]
Somehow moving in the maps is not possible by touchscreen, also not in development-tools in chrome and firefox. Might has something to do with "tap" in polymer?

**Comment by nhnb** [comment]
I cannot reproduce issues regarding moving the map on Chrome or Firefox on Android. Does the issue occur on http://leaflet-extras.github.io/leaflet-map/demo.html , too?

**Comment by nhnb** [comment]
Closing as not reproducible.
