### ISSUE TITLE
leaflet point is not working together with template is=dom-repeat

### ISSUE THREAD

**Issue by dezwei** [leaflet-extras/leaflet-map#44]
Hey guys
I have this issue:
![new bitmap image](https://cloud.githubusercontent.com/assets/13902960/9407908/f86b876e-480d-11e5-8e9d-653a0f5faf7e.png)
The leaflet point is created but not filled with longitude and latitude. the index is filled.

the locationarray is a [Object, Object, Object, Object, Object, Object] with
 0: Object
lat2: 52.3812073
long2: 13.3977036

I get this error  leaflet.js:6 Uncaught TypeError: Cannot read property 'lat' of null.

Is there a problem with dynamically generated leaflet points ?

**Comment by qtrandev** [comment]
I'm seeing this problem also. Any update if this is an issue or how to get around this?

**Comment by Compufreak345** [comment]
Can you try again? I think with my last pull-request https://github.com/leaflet-extras/leaflet-map/pull/41 accepted 2 days ago it should work now.

**Comment by qtrandev** [comment]
I can confirm pull-request #41 in the master branch fixes this problem. I can use leaflet-polyline now on my map. I downloaded a zip of the master branch and placed in the bower_components directory. I hope this gets released so I can use "bower install leaflet-map" to pull this working code. Thanks! @Compufreak345

**Comment by dezwei** [comment]
I can confirm too. Thanks
