### ISSUE TITLE
Leaflet in IronPages messes up tiles in IE

### ISSUE THREAD

**Issue by JustinCase1089** [leaflet-extras/leaflet-map#56]
Hi

I recently updated polymer and polymer elements and in IE leaflet messes up tiles. The code to reproduce is here

    <!doctype html>
    <html>
    <head>
        <script src='bower_components/webcomponentsjs/webcomponents.js'></script>
        <link rel='import' href='bower_components/polymer/polymer.html'>
        <link rel='import' href='bower_components/iron-pages/iron-pages.html'>
        <link rel='import' href='bower_components/leaflet-map/leaflet-map.html'>
    </head>
    <body unresolved>
        <iron-pages id='pageControl' selected='0'>
            <section>
                <leaflet-map style='width:1000px; height:1000px'></leaflet-map>
            </section>
        </iron-pages>
    </body>
</html>

What could be the problem?

**Comment by JustinCase1089** [comment]
Anyone with a clue on this one?

**Comment by songyanho** [comment]
You may call the LeafletJS map function `invalidateSize()`

Example:
```
<leaflet-map id="map" style='width:1000px; height:1000px'></leaflet-map>
```
```
if(this.$.map.map){
    this.$.map.map.invalidateSize();
}
```

Reference: http://stackoverflow.com/questions/24412325/resizing-a-leaflet-map-on-container-resize?answertab=active#tab-top

**Comment by JustinCase1089** [comment]
Thanks 😊
