### ISSUE TITLE
tiles didn't load

### ISSUE THREAD

**Issue by bastienarm** [leaflet-extras/leaflet-map#61]
Hi there,

I try to use the leaflet-map with polymer.
I add the leaflet-map tag inside my template, but when loading (and waiting) there is only one tile which is displayed (in the top left) with the original configuration (no leaflet-tilelayer, only set the latitude, longitude and zoom)

Does anyone have any idea?
Thanks a lot

![1](https://cloud.githubusercontent.com/assets/11157377/12392072/84d90efc-bdec-11e5-869d-3cb3c90e5135.png)

**Comment by bastienarm** [comment]
Finally found the solution, the leaflet-map was inside a div with a hidden$= attributes, which seems to be a little problem

**Comment by 456Q** [comment]
@bastienarm  Hi, i'm having the same issue. Can you please help me to get it fixed ?

Thanks
Stefan
