### ISSUE TITLE
zoom-in/zoom out button z-index

### ISSUE THREAD

**Issue by bastienarm** [leaflet-extras/leaflet-map#63]
Hi there,

The zoom-in/zoom-out button has this style : 

.leaflet-bottom {
	position: absolute;
	z-index: 1000;
	pointer-events: none;
}

Why do use a 1000 z-index?
I use polymer's paper-dialog which have a z-index of 103... So when opening the dialog, I see the zoom-in/zoom-out button.
Why did you use a this value?

**Comment by nhnb** [comment]
Hello Bastien,

I am sorry, that is something for the core leaflet project at https://github.com/Leaflet/Leaflet &lt;leaflet-map&gt; uses the stylesheet verbatim from leaflet.
